<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>07d2a8f4-be8b-4666-b3ba-0c88f15c2ad9</UserSecretsId>
		<PreserveCompilationContext>true</PreserveCompilationContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7" />
		<PackageReference Include="NSwag.AspNetCore" Version="14.7.0" />
		<PackageReference Include="OpenIddict.AspNetCore" Version="7.5.0" />
		<PackageReference Include="OpenIddict.Client.AspNetCore" Version="7.5.0" />
		<PackageReference Include="OpenIddict.Client.SystemNetHttp" Version="7.5.0" />
		<PackageReference Include="OpenIddict.Client.WebIntegration" Version="7.5.0" />
		<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="7.5.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
		<PackageReference Include="Resend" Version="0.4.0" />
	</ItemGroup>

</Project>